# Generated by Django 4.2.6 on 2023-11-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_profile_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profile",
            name="profile_image",
            field=models.ImageField(default="/blankprofile.png", upload_to="profile"),
        ),
    ]
