# Generated by Django 4.2.6 on 2023-11-28 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 21, 26, 3, 223672)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="post_images/"),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="profile_image",
            field=models.ImageField(default="blankprofile.png", upload_to="profile"),
        ),
    ]
