# Generated by Django 4.2.6 on 2023-11-28 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_post_created_at_alter_post_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 22, 5, 55, 14216)
            ),
        ),
    ]
