# Generated by Django 4.2.6 on 2023-11-28 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 22, 58, 53, 536823)
            ),
        ),
    ]
