# Generated by Django 4.2.6 on 2023-11-28 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_post_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 29, 0, 28, 18, 163439)
            ),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="profile_image",
            field=models.ImageField(
                default="profile_image/blank-profile-picture.png",
                upload_to="profile_image/",
            ),
        ),
    ]
