# Generated by Django 4.2.6 on 2023-11-30 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_post_created_at_likepost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likepost",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="likepost",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="likepost",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="likepost",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 1, 0, 32, 35, 924485)
            ),
        ),
    ]
