# Generated by Django 4.2.6 on 2023-11-30 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_remove_likepost_created_at_remove_likepost_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 1, 0, 33, 29, 99585)
            ),
        ),
    ]
