# Generated by Django 4.2.6 on 2023-11-30 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="likepost",
            name="post_id",
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 1, 0, 34, 0, 154219)
            ),
        ),
    ]
