# Generated by Django 4.2.6 on 2023-12-05 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_alter_followers_user_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 5, 17, 23, 15, 826066)
            ),
        ),
    ]
