# Generated by Django 4.2.6 on 2023-12-05 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_alter_followers_follower_alter_followers_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 5, 21, 8, 13, 619383)
            ),
        ),
    ]
