# Generated by Django 4.2.6 on 2023-12-05 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0035_remove_followers_user_alter_followers_follower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followers",
            name="user",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 5, 21, 56, 56, 475085)
            ),
        ),
    ]
